### ISSUE TITLE
Potential bug in nova_find_free_slot?

### ISSUE THREAD

**Issue by Icarusradio** [NVSL/linux-nova#112]
In `nova_find_free_slot`, I think this part of the code might have a potential bug
```c
if (!ret_node) {
	*prev = *next = NULL;
} else if (ret_node->range_high < range_low) {
	*prev = ret_node;
	tmp = rb_next(&ret_node->node);
	if (tmp) {
		*next = container_of(tmp, struct nova_range_node, node);
		check_next = 1;
	} else {
		*next = NULL;
	}
} else if (ret_node->range_low > range_high) {
	*next = ret_node;
	tmp = rb_prev(&ret_node->node);
	if (tmp) {
		*prev = container_of(tmp, struct nova_range_node, node);
		check_prev = 1;
	} else {
		*prev = NULL;
	}
} else {
	nova_dbg("%s ERROR: %lu - %lu overlaps with existing "
		 "node %lu - %lu\n",
		 __func__, range_low, range_high, ret_node->range_low,
		ret_node->range_high);
	return -EINVAL;
}
```
The problem exists in the second branch: it is possible that `ret_node->range_high < range_low` and `tmp->range_low < range_high`. Because when `nova_find_range_node(tree, range_low, NODE_BLOCK, &ret_node)` returns 0 and `ret_node != NULL`, it only guarantees that there is no node that `node->range_low <= range_low <= node->range_high`, it promises nothing about `range_high`. So it is possible that `tmp->range_low < range_high` and thus leads to an overlap.

**Comment by Andiry** [comment]
That is not gonna happen. nova_find_free_slot is used in nova_free_blocks,
meaning [range_low, range_high] has been allocated and not in the rb tree.
So it is impossible that tmp->range_low < range_high, which implies the
range we have allocated are still available in the free space tree.

Thanks,
Andiry

**Comment by Icarusradio** [comment]
Okay, I will close this issue.
