### ISSUE TITLE
how to let NOVA support xattr

### ISSUE THREAD

**Issue by Zhaoziwei0621** [NVSL/linux-nova#62]
I use nova managed PM(/dev/pmem0) in Openstack Swift as a Swift storage backend. But when I run a test, it reports an error:
>Apr 11 11:12:13 de84 object-server: STDERR: ERROR:root:Filesystem at 10 does not support xattr#
It seems like that NOVA do not support xattr extended attributes like other file systems, like XFS.
So, anybody can tell me how to solve this problem.

**Comment by Andiry** [comment]
Currently NOVA does not support xattr. It is on the to-do list.

**Comment by Zhaoziwei0621** [comment]
Andiry, Thank you so much.
Could you please tell me any other NVMFS which support xattr.

**Comment by Andiry** [comment]
You can try ext4-DAX or xfs-DAX.

**Comment by stevenjswanson** [comment]
How hard would this be do you think?

-steve

--
Composed on (and maybe dictated to) my phone.

**Comment by Andiry** [comment]
I don't think there is any difficulty. It just takes some effort.

**Comment by Zhaoziwei0621** [comment]
What is xfs-DAX and how to use it? Could you please elaborate on the details (a reference document will be great), or other possible solutions, because my time is currently tight.

**Comment by Andiry** [comment]
mkfs.xfs /dev/pmem0
mount -o dax /dev/pmem0 /mnt/ramdisk

**Comment by Zhaoziwei0621** [comment]
Thank you so much !!
