### ISSUE TITLE
Can't enable data integrity features

### ISSUE THREAD

**Issue by rajatkateja** [NVSL/linux-nova#63]
I tried enabling the metadata integrity features using the following (from Documentation/filesystems/nova.txt):
$> modprobe metadata_csum=1 data_csum=1 data_parity=1 wprotect=1
$> mount -t NOVA -o init /dev/pmem0 /mnt/pmem 

However, when I look at dmesg, I see 
"nova: measure timing 0, metadata checksum 0, inplace update 0, wprotect 0, data checksum 0, data parity 0, DRAM checksum 0"
which seems to imply that the data integrity features have not been enabled.

**Comment by luzh** [comment]
Could you try to remove any existing nova module and then modprobe?
1. umount /mnt/pmem
2. rmmod nova
3. modprobe nova metadata_csum=1 data_csum=1 data_parity=1 wprotect=1
4. mount -t NOVA -o init /dev/pmem0 /mnt/pmem

**Comment by rajatkateja** [comment]
That worked, thanks!
