### ISSUE TITLE
how to support the

### ISSUE THREAD

**Issue by Morry-lt** [NVSL/linux-nova#65]
I want to test the NOVA at the SSD. but when i mount and mkfs,it notes mount failed:Operation not supported.
Is nova only support pmem?Or I have to check some other Configuration?

**Comment by fengyuleidian0615** [comment]
You can to through https://nvdimm.wiki.kernel.org/ for setup based on DRAM to simulate PMEM

**Comment by Andiry** [comment]
Yes, NOVA only supports DAX devices, i.e. PMEM and emulated PMEM. NOVA does not support SSD.
