### ISSUE TITLE
how to map NVMM region as readonly upon mount?

### ISSUE THREAD

**Issue by fengyuleidian0615** [NVSL/linux-nova#69]
Hi @Andiry 

When I read through the [NOVA: A Log-structured File System for Hybrid Volatile/Non-vloatile Main Memories](https://www.usenix.org/system/files/conference/fast16/fast16-papers-xu.pdf) Section 4.8 NVMM Protection, 

_"NOVA uses the same protection mechanism that PMFS does. Upon mount, the whole NVMM region is mapped as read-only"_

I'm not sure which part of code implement this? is it NOVA specific or PMEM driver stuff, it would be good if you could point the location of code change :)

Thanks!

**Comment by Andiry** [comment]
That part is outside NOVA, implemented in nd_pmem.

Check this patch:
https://lkml.org/lkml/2017/8/3/88

**Comment by fengyuleidian0615** [comment]
Aha, that makes sense now.
Thanks for your prompt reply.
