### ISSUE TITLE
MAP_SYNC w/ NOVA fs

### ISSUE THREAD

**Issue by fengyuleidian0615** [NVSL/linux-nova#71]
Hi @Andiry 

MAP_SYNC feature merged in v4.15 vanilla kernel tried to call fdata_sync to flush dirty metadata and data down to media, this brings more robust filesystem consistence on top of journal.  As I read through NOVA FS implementation, both metadata and data are kept consistent, so by my limited understanding, equivalence of  MAP_SYNC in NOVA FS is not needed. 

Please correct me if I'm wrong somewhere.

thanks!

**Comment by Andiry** [comment]
Yes, you are right.

**Comment by pleiadesian** [comment]
According to [DAX support part in README](https://github.com/NVSL/linux-nova#dax-support), msync() in user space is needed. Why?

**Comment by Andiry** [comment]
You don't have to. When a file page is mmaped to user space, NOVA
releases control of it and it is the user's responsibility to ensure
consistency. User space can use any method: coarse-grained msync() or
fine-grained cache line flushing. It's about data consistency, not
metadata.

The issue itself is about the MAP_SYNC flag, which guarantees metadata
consistency. NOVA always guarantee metadata consistency.

Thanks,
Andiry
