### ISSUE TITLE
modprobe: FATAL: Module nova not found in directory /lib/modules/5.1.0+

### ISSUE THREAD

**Issue by urb31075** [NVSL/linux-nova#74]
I am executing a set of commands:
1) git clone https://github.com/NVSL/linux-nova.git
2) cd ./linux-nova
3) make menuconfig
CONFIG_LIBNVDIMM=y
CONFIG_BLK_DEV_PMEM=y
CONFIG_FS_DAX=y
CONFIG_NOVA_FS=y
4) sudo make bindeb-pkg
5) sudo dpkg -i linux-headers-5.1.0+_5.1.0+-1_amd64.deb
    sudo dpkg -i linux-image-5.1.0+_5.1.0+-1_amd64.deb
    sudo dpkg -i linux-image-5.1.0+-dbg_5.1.0+-1_amd64.deb
    sudo dpkg -i linux-libc-dev_5.1.0+-1_amd64.deb
6) sudo reboot
7) root@shd2:~# uname -r
    5.1.0+
8) root@shd2:~# modprobe nova
    modprobe: FATAL: Module nova not found in directory /lib/modules/5.1.0+

What else needs to be done?

**Comment by stevenjswanson** [comment]
Looks like you might have compiled nova directly into the kernel (“y”) rather than as module (“m”).

-Steve

**Comment by urb31075** [comment]
Thank! With CONFIG_NOVA_FS=m  it ok. 

root@shd2:~/linux-nova/fs/nova# modinfo ./nova.ko
filename:       /home/urb/linux-nova/fs/nova/./nova.ko
license:        GPL
description:    NOVA: A Persistent Memory File System
author:         Andiry Xu <jix024@cs.ucsd.edu>
srcversion:     51DBBD457C7EAF0D30E218C
depends:
retpoline:      Y
intree:         Y
name:           nova
vermagic:       5.1.0+ SMP mod_unload
parm:           measure_timing:Timing measurement (int)
parm:           metadata_csum:Protect metadata structures with replication and checksums (int)
parm:           wprotect:Write-protect pmem region and use CR0.WP to allow updates (int)
parm:           data_csum:Detect corruption of data pages using checksum (int)
parm:           data_parity:Protect file data using RAID-5 style parity. (int)
parm:           dram_struct_csum:Protect key DRAM data structures with checksums (int)
parm:           nova_dbgmask:Control debugging output (int)

I did not find documentation description of the parameters!
