### ISSUE TITLE
mount nova blocked

### ISSUE THREAD

**Issue by CCrainys** [NVSL/linux-nova#80]
Hi,
   Nova is a great job in nvm, I hope to test it to learn something from it. However, I encountered some problems during testing.
   1.  When I tested linux-nova in my virtual machine ubuntu18.04, I encountered a problem
   I use kernel option ""memmap=4G!12G" to create pmem0. And compile linux-nova master branch.
  According to nova.txt in documentation folder, 1. modprobe nova, 2. mount -t NOVA -o init /dev/pmem0 /mnt/ramdisk
  step 1 was successful, however, there were some problems in step2, as the picture shows,
<img width="690" alt="Screen Shot 2020-06-03 at 11 29 39 PM" src="https://user-images.githubusercontent.com/18700694/83657317-47e44680-a5f3-11ea-86d6-474b7cbf4e4a.png">
fitstly, output is "killed", secondly, the mount process was blocked, couldn't have any results.
Does virtual machine not support pmem0? If so, I can use physical machine.

2. According to your paper and nova.txt, it use some of dram as nvm to run nova. But intel has released real nvm, optane persistent memory, I wonder wether nova can run successfully in optane persistent memory.

Looking forward your reply! Thanks a lot

Best regards
Francis

**Comment by Andiry** [comment]
1. What is the output of dmesg? Can you try physical machine to see if the issue still exist?
2. I believe so. see https://www.usenix.org/conference/fast20/presentation/yang

**Comment by CCrainys** [comment]
Yeah, it works in physical machine. 
Thanks!
