### ISSUE TITLE
what is the most suitable installation environment to install NOVA fs

### ISSUE THREAD

**Issue by thomas-huangTw** [NVSL/linux-nova#82]
i have already try to install NOVA fs on ubuntu 18.04.1(kernel version 4.15.0-109-generic) VM.
I am executing a set of commands:

1. root@nova:~# git clone https://github.com/NVSL/linux-nova.git
2. root@nova:~# cd ./linux-nova-5.1
3. root@nova:~# make menuconfig
``` console
Device Drivers  --->
        <*> NVDIMM (Non-Volatile Memory Device) Support  --->
            <*>   PMEM: Persistent memory block device support (NEW)
            <*>   BLK: Block data window (aperture) device support (NEW)
            [*]   BTT: Block Translation Table (atomic sector updates)
    Processor type and features  --->
        <*> Support non-standard NVDIMMs and ADR protected memory
    Memory Management options  --->
        [*] Allow for memory hot-add
        [*]   Online the newly added memory blocks by default
        [*]   Allow for memory hot remove
        [*] Device memory (pmem, HMM, etc...) hotplug support
    File systems  --->
        [*] Direct Access (DAX) support
```
    CONFIG_LIBNVDIMM=y 
    CONFIG_BLK_DEV_PMEM=y
    CONFIG_FS_DAX=y
    CONFIG_NOVA_FS=m

4. root@nova:~# make -j4
5. root@nova:~# make modules_install
6. root@nova:~# make install

``` console
vim /etc/default/grub
GRUB_CMDLINE_LINUX="memmap=512M!4096M"
```

7. root@nova:~# modprobe nova
``` console
modprobe: FATAL: Module nova not found in directory /lib/modules/4.15.0-109-generic
```

What else needs to be done?
Or what is the most suitable ubuntu installation environment to install NOVA fs(version 18 or higher, cause need to install cdctl and impctl tool)?

**Comment by Andiry** [comment]
You are building NOVA kernel 5.1 on a 4.15 kernel. After building you have
to install the kernel and reboot to the 5.1 kernel. Then modprobe should
work.

**Comment by thomas-huangTw** [comment]
after upgrade kernel to 5.1.0, as below:
``` console
root@nova:~# uname -r
5.1.0-050100-generic
root@nova:~# lsb_release -a
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
``` 

and i install again:
root@nova:~# make menuconfig
``` console
Device Drivers  --->
        <*> NVDIMM (Non-Volatile Memory Device) Support  --->
            <*>   PMEM: Persistent memory block device support (NEW)
            <*>   BLK: Block data window (aperture) device support (NEW)
            [*]   BTT: Block Translation Table (atomic sector updates)
    Processor type and features  --->
        <*> Support non-standard NVDIMMs and ADR protected memory
    Memory Management options  --->
        [*] Allow for memory hot-add
        [*]   Online the newly added memory blocks by default
        [*]   Allow for memory hot remove
        [*] Device memory (pmem, HMM, etc...) hotplug support
    File systems  --->
        [*] Direct Access (DAX) support
        <M>   NOVA: log-structured file system for non-volatile memories
```
    CONFIG_LIBNVDIMM=y 
    CONFIG_BLK_DEV_PMEM=y
    CONFIG_FS_DAX=y
    CONFIG_NOVA_FS=m

1. root@nova:~# make -j4
2. root@nova:~# make modules_install
3. root@nova:~# make install

but i still get :
 root@nova:~# modprobe nova
modprobe: FATAL: Module nova not found in directory /lib/modules/5.1.0-050100-generic
 
What else needs to be done?
Or what is the most suitable ubuntu installation environment to install NOVA fs(version 18 or higher, cause need to install cdctl and impctl tool)?

**Comment by Andiry** [comment]
I think there is a misunderstanding somehow. The 5.1.0-050100-generic kernel you upgrade to is from Ubuntu, I guess? It is not the linux-nova kernel (also 5.1) that contains NOVA module.

After the make install command:

root@nova:~# make -j4
root@nova:~# make modules_install
root@nova:~# make install

Reboot the system (or VM), in grub, boot into the 5.1 kernel installed (not the 5.1.0-050100-generic one), and then try modprobe.

BTW: I suggest trying NOVA on bare-metal machine, not VM. We have seen some issues with NOVA running on VM.
