### ISSUE TITLE
unable to handle kernel paging request at ffff91a53fffffe0 

### ISSUE THREAD

**Issue by little-dog007** [NVSL/linux-nova#83]
I had this problem when i  mount NOVA with "sudo mount -t NOVA -o init /dev/pmem0 /mnt/ramdisk".My environment is vmware + linux-nova5.1.
I compile and install successfully. 
![p2](https://user-images.githubusercontent.com/58713739/87747559-45961e80-c826-11ea-82f0-cccc9a41fc85.png)

![2](https://user-images.githubusercontent.com/58713739/87747444-f64fee00-c825-11ea-877f-84929586dd6d.png)

 I found the problem was that I couldn't read a variable "curr_page->page_taill.next_page".However,i can get the address of  "curr_page->page_tail";
It's not an empty pointer problem, and the address is in the kernel virtual address range, so I' m confused.
Does anyone have the same problem as me and find a solution?

PS:when we mount a new nova instance,the nova_rebuild_inode function call the nova_rebuild_file_inode_tree,why not nova_rebuild_dir_inode_tree? I think root inode is a dir inode.

**Comment by Andiry** [comment]
Can you try on a bare-metal machine instead of VM to see if the issue still
exists?

Indeed root inode is a dir inode and it should call
nova_rebuild_dir_inode_tree. I suspect there is something messed up when it
runs on VM.

**Comment by little-dog007** [comment]
I experimented on the virtual machine vmware + ubantu 18.04. It made the same mistake.Next,i will try on a bare-metal machine.
