### ISSUE TITLE
mount /dev/pmem0 on /mnt/ramdisk fail:stale file handle

### ISSUE THREAD

**Issue by little-dog007** [NVSL/linux-nova#84]
I tried on tencent cloud server.
 Here are my operations:
1.edit /boot/grub/grub  ,add memmap=16G!8G
![err1](https://user-images.githubusercontent.com/58713739/88358853-302f7000-cda3-11ea-8983-5df46ad20110.PNG)

2.sudo mkdir /mnt/ramdisk
3.sudo modprobe nova
4.sudo mount -t NOVA -o init /dev/pmem0 /mnt/ramdisk
But it's wrong.
![err2](https://user-images.githubusercontent.com/58713739/88358985-a59b4080-cda3-11ea-966d-214d602e0155.PNG)

![err3](https://user-images.githubusercontent.com/58713739/88358987-a59b4080-cda3-11ea-80de-f8d6f5746382.PNG)

Does anyone know how to solve this problem?

**Comment by Andiry** [comment]
I am still suspecting this is a VM issue. The metadata of physical inode on pmem does not match the vnode. For example, inode number for root inode should be 1 but read as 0.

Still, I am suggesting trying on bare-metal machine first.
