### ISSUE TITLE
NOVA-strict

### ISSUE THREAD

**Issue by Xarboule** [NVSL/linux-nova#90]
In the SplitFS paper (SOSP19) is mentioned a "NOVA-strict" mode.
1) Do you have an option somewhere to enable this mode ?
2) Does this strict mode give us linearizability ? If not, what kind of durability guarantees does it provide ?

Thank you !

**Comment by Andiry** [comment]
1. Please check the module parameters in fs/nova/super.c. With strict mode we enable metadata_csum, data_csum, data_parity, dram_struct_csum and wprotect.

2. Even the relaxed mode gives linearizability. NOVA guarantees both data and metadata are linearized and persisted when the write() returns. If user uses DAX-mmap, then it is the user's responsibility to make data durable.
