### ISSUE TITLE
Ignore MAP_SYNC instead of unsupport it

### ISSUE THREAD

**Issue by pleiadesian** [NVSL/linux-nova#99]
To guarantee metadata consistency, applications will manually call many `fsync`s after `mmap` with `MAP_SYNC` failed, as shown by [this issue in pmdk](https://github.com/pmem/pmdk/issues/5202). But in NOVA, metadata can be kept consistent without `fsync` or `MAP_SYNC`, so the `fsync`s generated by applications are redundant and significantly decrease performance. 
So, I think to support MAP_SYNC and ignore it can match better with the behavior of other DAX-supporting file systems, as stated by [this comment](https://github.com/pmem/pmdk/issues/5202#issuecomment-822324934).

**Comment by Andiry** [comment]
I think NOVA should ignore MAP_SYNC. Care to send a PR? I can take a look at it but it may take a while.

**Comment by pleiadesian** [comment]
I'll handle it this weekend :)

**Comment by Andiry** [comment]
Really appreciate your help.
